use_frameworks!

platform :ios, '9.0'

target 'LBJSDK_Example' do
  pod 'LBJSDK', :path => '../'

  target 'LBJSDK_Tests' do
    inherit! :search_paths

  pod 'FBSnapshotTestCase'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'ReactiveObjC'
  pod 'SDWebImage'
  end
end
